version: 1.0.{branch}.{build}

clone_depth: 10
shallow_clone: true

cache:
  - '%APPDATA%\npm-cache'
  - node_modules
build:
  verbosity: minimal

environment:
  nodejs_version: "11"

install:
  - choco install firefox
  - choco install googlechrome
  - ps: Install-Product node $env:nodejs_version
  - npm install

build_script:
  - npm run lint
  - npm run build

test_script:
  - npm run test:firefox -- --single-run
  - npm run test:chrome -- --single-run

deploy: off
