name: "gh-pages"

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - run: npm run build
      - run: git fetch origin gh-pages
      - run: git switch gh-pages
      - run: |
          shopt -s extglob
          rm -rf !(dist)
          mv -f dist/* . && rm -rf dist
      - run: ls -la
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - run: git commit -am "✨ ${{ steps.get_version.outputs.VERSION }}"
      - run: git push origin gh-pages
